language: android
sudo: required
jdk: oraclejdk8
dist: trusty

before_install:
  - unset JAVA_OPTS
  - export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
  - touch $HOME/.android/repositories.cfg
  - chmod +x gradlew

android:
  components:
      - tools
      - android-30
      - platform-tools
      - tools
      - extra-android-m2repository
  licenses:
    - '.+'



before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache



