language: android
sudo: required
jdk: oraclejdk11
dist: trusty

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-android-m2repository
    - - android-$ANDROID_EMULATOR_LEVEL
    - sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_LEVEL
  licenses:
    - '.+'

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager --licenses

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache


addons:
sonarqube:
        organization: "grupotres"
        token:
          secure: "4b4e8b96a8e6c7116c456d841a00a7d504b8a51a" # encrypted value of your token

          script:
            - sonnar-scanner
